import { getUserInfoAction } from "@/app/actions";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userInfo = await getUserInfoAction();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-[960px] max-w-[100vw] mx-auto p-4">
          <ul className="flex gap-4">
            <li>
              <a href="/" className="text-3xl font-semibold">
                HOME
              </a>
            </li>
            {userInfo?.name !== undefined ? (
              <li className="ml-auto">hi, {userInfo.name}</li>
            ) : (
              <>
                <li className="ml-auto">
                  <a href="/login">Login</a>
                </li>
                <li>
                  <a href="/register">register</a>
                </li>
              </>
            )}
          </ul>
          <main className="py-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
